'use strict';

// eslint-disable-next-line no-unused-vars
const config = {
  style: 'mapbox://styles/mapbox/standard',
  accessToken:
    'pk.eyJ1IjoibWFwYm94LWNvbW11bml0eSIsImEiOiJja2tkN21jcjAwMG51MnBxdHAxemdueGpzIn0.e0IzLkytGq4pcGGieP8KNA',
  CSV: './Sample_Data.csv',
  center: [-120.234, 47.398],
  zoom: 6,
  title: 'Program List',
  description:
    'TO REPLACE',
  sideBarInfo: ['School'],
  popupInfo: ['School'],
  filters: [
    {
      type: 'dropdown',
      title: 'Programs: ',
      columnHeader: 'Programslist',
      listItems: [
“Accounting”,
"Accounting and Business/Management”,
“Accounting and Finance”,
"Accounting and Related Services (Other)”, 
"Accounting Technology/Technician and Bookkeeping”, 
"Acoustics”, 
"Acting”, 
"Actuarial Science”, "Acupuncture and Oriental Medicine”, 
"Administration of Special Education”, 
"Administrative Assistant and Secretarial Science (General)”,
"Adult and Continuing Education Administration”, 
"Adult and Continuing Education and Teaching”,
"Adult Development and Aging”, 
"Adult Health Nurse/Nursing”, 
"Adult Literacy Tutor/Instructor”,
"Advanced General Dentistry”, 
"Advanced Legal Research/Studies (General)”, 
"Advanced/Graduate Dentistry and Oral Sciences (Other)”, 
"Advertising”, 
"Aeronautical/Aerospace Engineering Technology/Technician”, 
"Aeronautics/Aviation/Aerospace Science and Technology (General)”, 
"Aerospace Ground Equipment Technology”,
"Aerospace Physiology and Medicine”, 
"Aerospace/Aeronautical/Astronautical/Space Engineering (General)”,
"African Languages/Literatures/Linguistics”, 
"African Studies”, 
"AfricanAmerican/Black Studies”, 
"Agribusiness/Agricultural Business Operations”, 
"Agricultural and Extension Education Services”, 
"Agricultural and Food Products Processing”, 
"Agricultural and Horticultural Plant Breeding”, 
"Agricultural Animal Breeding”,
"Agricultural Business and Management (General)”,
"Agricultural Business and Management (Other)”, 
"Agricultural Business Technology/Technician”,
"Agricultural Communication/Journalism”,
"Agricultural Economics”,
"Agricultural Engineering”, 
"Agricultural Mechanization (General)”, 
"Agricultural Production Operations (General)”, 
"Agricultural Production Operations (Other)”, 
"Agricultural Public Services (Other)”, 
"Agricultural Teacher Education”, 
"Agricultural/Animal/Plant/Veterinary Science and Related Fields (Other)”, 
"Agricultural/Farm Supplies Retailing and Wholesaling”,
"Agriculture (General)”, 
"Agriculture/Veterinary Preparatory Programs (Other)”, 
"Agroecology and Sustainable Agriculture”, 
"Agronomy and Crop Science”,
"Air and Space Operations Technology”, 
"Air Traffic Controller”,
"Air Transportation (Other)”, 
"Aircraft Powerplant Technology/Technician”, 
"Airframe Mechanics and Aircraft Maintenance Technology/Technician”, 
"Airline/Commercial/Professional Pilot and Flight Crew”, 
"Allied Health and Medical Assisting Services (Other)”,
"Allied Health Diagnostic/Intervention/Treatment Professions (Other)”,
"Alternative and Complementary Medicine and Medical Systems (General)”, 
"Alternative and Complementary Medicine and Medical Systems (Other)”, 
"American History (United States)”, 
"American Government and Politics (United States)”, 
"American Indian/Native American Languages/Literatures/Linguistics”, 
"American Indian/Native American Studies”, 
"American Literature (United States)”, 
"American Sign Language (ASL)”,
"American Sign Language (Other)”, 
"American/U.S. Law/Legal Studies/Jurisprudence”, 
"American/United States Studies/Civilization”,
"Analysis and Functional Analysis”, 
"Analytical Chemistry”, 
"Anatomy”,
"Ancient Near Eastern and Biblical Languages/Literatures/Linguistics”,
"Ancient Studies/Civilization”,
"Ancient/Classical Greek Language and Literature”, 
"Anesthesiologist Assistant”, 
"Animal Behavior and Ethology”,
"Animal Genetics”, 
"Animal Health”,
"Animal Nutrition”,
"Animal Physiology”, 
"Animal Sciences (General)”,
"Animal Sciences (Other)”, 
"Animal Training”, 
"Animal/Livestock Husbandry and Production”, 
"AnimalAssisted Therapy”,
"Animation/Interactive Technology/Video Graphics/Special Effects”, 
"Anthropology (General)”,
"Anthropology (Other)”, 
"Anthrozoology”,
"Apparel and Accessories Marketing Operations”, 
"Apparel and Textile Manufacture”,
"Apparel and Textile Marketing Management”,
"Apparel and Textiles (General)”, 
"Apparel and Textiles (Other)”,
"Applied and Professional Ethics”,
"Applied Behavior Analysis”,
"Applied Demography”, 
"Applied Economics”, 
 "Applied Engineering”,
 "Applied Engineering Technologies/Technicians”, 
 "Applied Horticulture/Horticultural Business Services (Other)”, 
 "Applied Horticulture/Horticulture Operations (General)”, 
 "Applied Linguistics”,
 "Applied Mathematics (General)”, 
 "Applied Mathematics (Other)”, 
 "Applied Psychology”, 
 "Applied Statistics (General)”,
 "Applied/Public Sociology”, 
 "Aquaculture”, 
 "Aquatic Biology/Limnology”,
 "Arabic Language and Literature”, 
 "Archeology”,
 "Architectural and Building Sciences/Technology”,
 "Architectural Design”, 
 "Architectural Drafting and Architectural CAD/CADD”,
 "Architectural Engineering”,
 "Architectural Engineering Technologies/Technicians”, 
 "Architectural History and Criticism (General)”, 
 "Architectural Sciences and Technology (Other)”, 
 "Architectural Studies”, 
 "Architectural Technology/Technician”, 
 "Architecture”, 
 "Architecture and Related Services (Other)”, 
 "Archives/Archival Administration”, 
 "Area Studies (Other)”, 
 "Area/Ethnic/Cultural/Gender/Group Studies (Other)”,
 "Art History/Criticism and Conservation”, 
 "Art Teacher Education”, 
 "Art Therapy/Therapist”, 
 "Art/Art Studies (General)”,
 "Artificial Intelligence”, 
 "Arts in Medicine/Health”, 
 "Arts/Entertainment/Media Management (General)”, 
 "Arts/Entertainment/Media Management (Other)”,
 "Asian Studies/Civilization”, 
 "AsianAmerican Studies”, 
 "Assistive/Augmentative Technology and Rehabilitation Engineering”,
 "Astronautical Engineering”,
 "Astronomy”, 
 "Astronomy and Astrophysics (Other)”,
 "Astrophysics”, 
 "Athletic Training/Trainer”,
 "Atmospheric Chemistry and Climatology”,
 "Atmospheric Physics and Dynamics”, 
 "Atmospheric Sciences and Meteorology (General)”,
 "Atmospheric Sciences and Meteorology (Other)”, 
 "Atomic/Molecular Physics”, 
 "Audio Engineering Technology/Technician”, 
 "Audiology/Audiologist”, 
 "Audiology/Audiologist and SpeechLanguage Pathology/Pathologist”, 
 "Audiovisual Communications Technologies/Technicians (Other)”, 
 "Auditing”, 
 "Autobody/Collision and Repair Technology/Technician”, 
 "Automation Engineer Technology/Technician”, 
 "Automobile/Automotive Mechanics Technology/Technician”, 
 "Automotive Engineering Technology/Technician”, 
 "Aviation/Airway Management and Operations”, 
 "Ayurvedic Medicine/Ayurveda”, 
 "Baking and Pastry Arts/Baker/Pastry Chef”,
 "Ballet”, 
 "Banking and Financial Support Services”, 
 "Banking/Corporate/Finance/Securities Law”,
 "Behavioral Aspects of Health”,
 "Behavioral Neuroscience”, 
 "Behavioral Sciences”,
 "Bible/Biblical Studies”,
 "Bilingual and Multilingual Education”, 
 "Bilingual/Multilingual/Multicultural Education (Other)”, 
 "Biochemical Engineering”, 
 "Biochemistry”, 
 "Biochemistry and Molecular Biology”,
 "Biochemistry/Biophysics and Molecular Biology (Other)”, 
 "Bioengineering and Biomedical Engineering”, 
 "Bioethics/Medical Ethics”, 
 "Bioinformatics”, 
 "Biological and Biomedical Sciences (Other)”, 
 "Biological and Physical Sciences”, 
 "Biological/Biosystems Engineering”, 
 "Biology Teacher Education”
      ],
    },
  ],
};
