'use strict';

// eslint-disable-next-line no-unused-vars
const config = {
  style: 'mapbox://styles/mapbox/streets-v12',
  accessToken:
    'pk.eyJ1IjoiYW5uYXNpbGxlcnMiLCJhIjoiY2xweDZ2a2RrMGk1ZjJqbnJnc25pZGhyYSJ9.0kwnSzA5FG6Cmse2aBC4AQ', //DON'T CHANGE - should end in AQ
  CSV: './Sample_Data.csv',
  center: [-94, 38],
  zoom: 4,
  title: 'TO REPLACE ',
  description:
    'TO REPLACE',
  sideBarInfo: ['School', 'CITY', 'STATE'],
  popupInfo: ['School'],
  filters: [
    {
      type: 'dropdown',
      title: 'Programs Offered: ',
      columnHeader: 'Programslist',
      listItems: [
`Accounting`,
`Accounting and Business/Management`,
`Accounting and Finance`,
`Accounting and Related Services (Other)`, 
`Accounting Technology/Technician and Bookkeeping`, 
`Acoustics`, 
`Acting`, 
`Actuarial Science`, `Acupuncture and Oriental Medicine`, 
`Administration of Special Education`, 
`Administrative Assistant and Secretarial Science (General)`,
`Adult and Continuing Education Administration`, 
`Adult and Continuing Education and Teaching`,
`Adult Development and Aging`, 
`Adult Health Nurse/Nursing`, 
`Adult Literacy Tutor/Instructor`,
`Advanced General Dentistry`, 
`Advanced Legal Research/Studies (General)`, 
`Advanced/Graduate Dentistry and Oral Sciences (Other)`, 
`Advertising`, 
`Aeronautical/Aerospace Engineering Technology/Technician`, 
`Aeronautics/Aviation/Aerospace Science and Technology (General)`, 
`Aerospace Ground Equipment Technology`,
`Aerospace Physiology and Medicine`, 
`Aerospace/Aeronautical/Astronautical/Space Engineering (General)`,
`African Languages/Literatures/Linguistics`, 
`African Studies`, 
`AfricanAmerican/Black Studies`, 
`Agribusiness/Agricultural Business Operations`, 
`Agricultural and Extension Education Services`, 
`Agricultural and Food Products Processing`, 
`Agricultural and Horticultural Plant Breeding`, 
`Agricultural Animal Breeding`,
`Agricultural Business and Management (General)`,
`Agricultural Business and Management (Other)`, 
`Agricultural Business Technology/Technician`,
`Agricultural Communication/Journalism`,
`Agricultural Economics`,
`Agricultural Engineering`, 
`Agricultural Mechanization (General)`, 
`Agricultural Production Operations (General)`, 
`Agricultural Production Operations (Other)`, 
`Agricultural Public Services (Other)`, 
`Agricultural Teacher Education`, 
`Agricultural/Animal/Plant/Veterinary Science and Related Fields (Other)`, 
`Agricultural/Farm Supplies Retailing and Wholesaling`,
`Agriculture (General)`, 
`Agriculture/Veterinary Preparatory Programs (Other)`, 
`Agroecology and Sustainable Agriculture`, 
`Agronomy and Crop Science`,
`Air and Space Operations Technology`, 
`Air Traffic Controller`,
`Air Transportation (Other)`, 
`Aircraft Powerplant Technology/Technician`, 
`Airframe Mechanics and Aircraft Maintenance Technology/Technician`, 
`Airline/Commercial/Professional Pilot and Flight Crew`, 
`Allied Health and Medical Assisting Services (Other)`,
`Allied Health Diagnostic/Intervention/Treatment Professions (Other)`,
`Alternative and Complementary Medicine and Medical Systems (General)`, 
`Alternative and Complementary Medicine and Medical Systems (Other)`, 
`American History (United States)`, 
`American Government and Politics (United States)`, 
`American Indian/Native American Languages/Literatures/Linguistics`, 
`American Indian/Native American Studies`, 
`American Literature (United States)`, 
`American Sign Language (ASL)`,
`American Sign Language (Other)`, 
`American/U.S. Law/Legal Studies/Jurisprudence`, 
`American/United States Studies/Civilization`,
`Analysis and Functional Analysis`, 
`Analytical Chemistry`, 
`Anatomy`,
`Ancient Near Eastern and Biblical Languages/Literatures/Linguistics`,
`Ancient Studies/Civilization`,
`Ancient/Classical Greek Language and Literature`, 
`Anesthesiologist Assistant`, 
`Animal Behavior and Ethology`,
`Animal Genetics`, 
`Animal Health`,
`Animal Nutrition`,
`Animal Physiology`, 
`Animal Sciences (General)`,
`Animal Sciences (Other)`, 
`Animal Training`, 
`Animal/Livestock Husbandry and Production`, 
`AnimalAssisted Therapy`,
`Animation/Interactive Technology/Video Graphics/Special Effects`, 
`Anthropology (General)`,
`Anthropology (Other)`, 
`Anthrozoology`,
`Apparel and Accessories Marketing Operations`, 
`Apparel and Textile Manufacture`,
`Apparel and Textile Marketing Management`,
`Apparel and Textiles (General)`, 
`Apparel and Textiles (Other)`,
`Applied and Professional Ethics`,
`Applied Behavior Analysis`,
`Applied Demography`, 
`Applied Economics`,  
`Applied Engineering`,
`Applied Engineering Technologies/Technicians`, 
`Applied Horticulture/Horticultural Business Services (Other)`, 
`Applied Horticulture/Horticulture Operations (General)`, 
`Applied Linguistics`,
`Applied Mathematics (General)`, 
`Applied Mathematics (Other)`, 
`Applied Psychology`, 
`Applied Statistics (General)`,
`Applied/Public Sociology`, 
`Aquaculture`, 
`Aquatic Biology/Limnology`,
`Arabic Language and Literature`, 
`Archeology`,
`Architectural and Building Sciences/Technology`,
`Architectural Design`, 
`Architectural Drafting and Architectural CAD/CADD`,
`Architectural Engineering`,
`Architectural Engineering Technologies/Technicians`, 
`Architectural History and Criticism (General)`, 
`Architectural Sciences and Technology (Other)`, 
`Architectural Studies`, 
`Architectural Technology/Technician`, 
`Architecture`, 
`Architecture and Related Services (Other)`, 
`Archives/Archival Administration`, 
`Area Studies (Other)`, 
`Area/Ethnic/Cultural/Gender/Group Studies (Other)`,
`Art History/Criticism and Conservation`, 
`Art Teacher Education`, 
`Art Therapy/Therapist`, 
`Art/Art Studies (General)`,
`Artificial Intelligence`, 
`Arts in Medicine/Health`, 
`Arts/Entertainment/Media Management (General)`, 
`Arts/Entertainment/Media Management (Other)`,
`Asian Studies/Civilization`, 
`AsianAmerican Studies`, 
`Assistive/Augmentative Technology and Rehabilitation Engineering`,
`Astronautical Engineering`,
`Astronomy`, 
`Astronomy and Astrophysics (Other)`,
`Astrophysics`, 
`Athletic Training/Trainer`,
`Atmospheric Chemistry and Climatology`,
`Atmospheric Physics and Dynamics`, 
`Atmospheric Sciences and Meteorology (General)`,
`Atmospheric Sciences and Meteorology (Other)`, 
`Atomic/Molecular Physics`, 
`Audio Engineering Technology/Technician`, 
`Audiology/Audiologist`, 
`Audiology/Audiologist and SpeechLanguage Pathology/Pathologist`, 
`Audiovisual Communications Technologies/Technicians (Other)`, 
`Auditing`, 
`Autobody/Collision and Repair Technology/Technician`, 
`Automation Engineer Technology/Technician`, 
`Automobile/Automotive Mechanics Technology/Technician`, 
`Automotive Engineering Technology/Technician`, 
`Aviation/Airway Management and Operations`, 
`Ayurvedic Medicine/Ayurveda`, 
`Baking and Pastry Arts/Baker/Pastry Chef`,
`Ballet`, 
`Banking and Financial Support Services`, 
`Banking/Corporate/Finance/Securities Law`,
`Behavioral Aspects of Health`,
`Behavioral Neuroscience`, 
`Behavioral Sciences`,
`Bible/Biblical Studies`,
`Bilingual and Multilingual Education`, 
`Bilingual/Multilingual/Multicultural Education (Other)`, 
`Biochemical Engineering`, 
`Biochemistry`, 
`Biochemistry and Molecular Biology`,
`Biochemistry/Biophysics and Molecular Biology (Other)`, 
`Bioengineering and Biomedical Engineering`, 
`Bioethics/Medical Ethics`, 
`Bioinformatics`, 
`Biological and Biomedical Sciences (Other)`, 
`Biological and Physical Sciences`, 
`Biological/Biosystems Engineering`, 
`Biology Teacher Education`,
`Biology/Biological Sciences (General)`,
`Biology/Biotechnology Technology/Technician`,
`Biomathematics/Bioinformatics/Computational Biology (Other)`, 
`Biomechanics`, 
`Biomedical Sciences (General)`, 
`Biomedical Technology/Technician`, 
`Biometry/Biometrics`,
`Biophysics`,
`Biopsychology`,
`Biostatistics`,
`Biotechnology`,
`Blood Bank Technology Specialist`, 
`Botany/Plant Biology`, 
`Botany/Plant Biology (Other)`,
`Brass Instruments`, 
`Brewing Science`, 
`Broadcast Journalism`, 
`Building/Construction Finishing/Management/Inspection (Other)`,
`Building/Construction Site Management/Manager`, 
`Business Administration and Management (General)`, 
`Business Administration/Management and Operations (Other)`, 
`Business Analytics`, 
`Business and Innovation/Entrepreneurship Teacher Education`,
`Business Family and Consumer Sciences/Human Sciences`,
`Business Statistics`,
`Business/Commerce (General)`, 
`Business/Corporate Communications (General)`,
`Business/Management/Marketing/Related Support Services (Other)`, 
`Business/Managerial Economics`, 
`Business/Office Automation/Technology/Data Entry`, 
`CAD/CADD Drafting and/or Design Technology/Technician`, 
 `Cardiopulmonary Technology/Technologist`, 
 `Cardiovascular Science`,
 `Cardiovascular Technology/Technologist`, 
 `Catholic Studies`,
 `Cell Biology and Anatomy`, 
 `Cell Physiology`, 
 `Cell/Cellular and Molecular Biology`, 
 `Cell/Cellular Biology and Anatomical Sciences (Other)`, 
 `Cell/Cellular Biology and Histology`, 
 `Celtic Languages/Literatures/Linguistics`,
 `Ceramic Arts and Ceramics`,
 `Ceramic Sciences and Engineering`, 
 `Chaplain/Chaplaincy Studies`, 
 `Chemical and Biomolecular Engineering`,
 `Chemical Engineering`, 
 `Chemical Physics`,
 `Chemical Technology/Technician`, 
 `Cheminformatics/Chemistry Informatics`,
 `Chemistry (General)`,
 `Chemistry (Other)`, 
 `Chemistry Teacher Education`, 
 `Child Care and Support Services Management`, 
 `Child Care Provider/Assistant`, 
 `Child Development`, 
 `Children’s and Adolescent Literature`, 
 `Children and Youth Library Services`, 
 `Chinese Language and Literature`,
 `Chinese Studies`, 
 `Chiropractic`, 
 `Christian Studies`, 
 `Church Planting`, 
 `Cinematography and Film/Video Production`,
 `City/Urban/Community/Regional Planning`, 
 `Civil Drafting and Civil Engineering CAD/CADD`, 
 `Civil Engineering (General)`, 
 `Civil Engineering (Other)`,
 `Civil Engineering Technologies/Technicians`, 
 `Classical/Ancient Mediterranean/Near Eastern Studies and Archaeology`, 
 `Classics and Classical Languages/Literatures/Linguistics (General)`, 
 `Classics and Classical Languages/Literatures/Linguistics (Other)`,
 `Climate Science`, 
 `Clinical and Industrial Drug Development`,
 `Clinical and Translational Science`,
 `Clinical Child Psychology`,
 `Clinical Laboratory Science/Medical Technology/Technologist`, 
 `Clinical Nurse Leader`, 
 `Clinical Nurse Specialist`,
 `Clinical Nutrition/Nutritionist`,
 `Clinical Pastoral Counseling/Patient Counseling`, 
 `Clinical Psychology`,
 `Clinical Research Coordinator`, 
 `Clinical/Counseling and Applied Psychology (Other)`, 
 `Clinical/Hospital/Managed Care Pharmacy`, 
 `Clinical/Medical Laboratory Assistant`,
 `Clinical/Medical Laboratory Science and Allied Professions (Other)`, 
 `Clinical/Medical Laboratory Technician`, 
 `Clinical/Medical Social Work`,
 `Cloud Computing`, 
 `Cognitive Psychology and Psycholinguistics`, 
 `Cognitive Science (General)`, 
 `College Student Counseling and Personnel Services`,
 `College/Postsecondary/University Teaching`, 
 `Comedy Writing and Performance`, 
 `Commercial and Advertising Art`, 
 `Commercial Photography`,
 `Communication (General)`, 
 `Communication and Media Studies (Other)`, 
 `Communication Arts and Literature Teacher Education`, 
 `Communication Disorders Sciences and Services (Other)`, 
 `Communication Management and Strategic Communications`, 
 `Communication Sciences and Disorders (General)`,
 `Communication/Journalism/Related Programs (Other)`,
 `Communications Technologies/Technicians and Support Services (Other)`, 
 `Communications Technology/Technician`, 
 `Community College Administration`, 
 `Community Health and Preventive Medicine`,
 `Community Health Services/Liaison/Counseling`, 
 `Community Organization and Advocacy`, 
 `Community Psychology`, 
 `Community/Environmental/SociallyEngaged Art`,
 `Comparative and Laboratory Animal Medicine`, 
 `Comparative Group Studies`,
 `Comparative Law`, 
 `Comparative Literature`,
 `Comparative Psychology`,
 `Computational and Applied Mathematics`,
 `Computational Biology`, 
 `Computational Mathematics`,
 `Computational Science`, 
 `Computer and Information Sciences (General)`,
 `Computer and Information Sciences and Support Services (Other)`, 
 `Computer and Information Sciences/ Other`,
 `Computer and Information Systems Security/Auditing/Information Assurance`, 
 `Computer Engineering (General)`, 
 `Computer Engineering (Other)`,
 `Computer Engineering Technologies/Technicians (Other)`, 
 `Computer Engineering Technology/Technician`, 
 `Computer Game Programming`,
 `Computer Graphics`, 
 `Computer Hardware Engineering`, 
 `Computer Programming (Other)`,
 `Computer Programming/Programmer (General)`, 
 `Computer Programming/Specific Applications`, 
 `Computer Programming/Specific Platforms`, 
 `Computer Science`,
 `Computer Software and Media Applications (Other)`, 
 `Computer Software Engineering`, 
 `Computer Software Technology/Technician`, 
 `Computer Support Specialist`, 
 `Computer Systems Analysis/Analyst`, 
 `Computer Systems Networking and Telecommunications`, 
 `Computer Teacher Education`, 
 `Computer/Computer Systems Technology/Technician`, 
 `Computer/Information Technology Services Administration and Management (Other)`, 
 `Condensed Matter and Materials Physics`, 
 `Conducting`,
 `Conservation Biology`, 
 `Construction Engineering`, 
 `Construction Engineering Technology/Technician`,
 `Construction Management (General)`, 
 `Consumer Economics`, 
 `Consumer Merchandising/Retailing Management`,
 `Consumer Services and Advocacy`, 
 `Contemplative Studies/Inquiry`, 
 `Corrections`, 
 `Corrections Administration`, 
 `Corrections and Criminal Justice (Other)`,
 `Costume Design`, 
 `Counseling Psychology`, 
 `Counselor Education/School Counseling and Guidance Services`, 
 `Court Reporting and Captioning/Court Reporter`, 
 `Crafts/Craft Design/Folk Art and Artisanry`, 
 `Creative Writing`,
 `Criminal Justice and Corrections (General)`, 
 `Criminal Justice/Law Enforcement Administration`, 
 `Criminal Justice/Police Science`,
 `Criminal Justice/Safety Studies`,
 `Criminal Law and Procedure`, 
 `Criminalistics and Criminal Science`, 
 `Criminology`, 
 `Crisis/Emergency/Disaster Management`, 
 `Critical Care Nursing`, 
 `Critical Infrastructure Protection`,
 `Crop Production`, 
 `Culinary Arts and Related Services (Other)`, 
 `Culinary Arts/Chef Training`, 
 `Culinary Science/Culinology`, 
 `Cultural Anthropology`, 
 `Cultural Resource Management and Policy Analysis`, 
 `Cultural Studies and Comparative Literature`,
 `Cultural Studies/Critical Theory and Analysis`, 
 `Curriculum and Instruction`, 
 `Customer Service Management`, 
 `Cyber/Computer Forensics and Counterterrorism`, 
 `Cyber/Electronic Operations and Warfare`, 
 `Cybersecurity Defense Strategy/Policy`,
 `Cytogenetics/Genetics/Clinical Genetics Technology/Technologist`, 
 `Cytotechnology/Cytotechnologist`,
 `Dairy Science`,
 `Dance (General)`, 
 `Dance (Other)`,
 `Dance Therapy/Therapist`, 
 `Danish Language and Literature`, 
 `Data Analytics (General)`, 
 `Data Analytics (Other)`,
 `Data Modeling/Warehousing and Database Administration`, 
 `Data Processing and Data Processing Technology/Technician`, 
 `Data Science (General)`,
 `Data Science (Other)`, 
 `Data Visualization`, 
 `Deaf Studies`, 
 `Demography and Population Studies`, 
 `Dental Assisting/Assistant`, 
 `Dental Clinical Sciences (General)`,
 `Dental Hygiene/Hygienist`, 
 `Dental Laboratory Technology/Technician`, 
 `Dental Materials`,
 `Dental Public Health and Education`,
 `Dental Services and Allied Professions (Other)`,
 `Dentistry`, 
 `Design and Applied Arts (Other)`,
 `Design and Visual Communications (General)`, 
 `Development Economics and International Development`, 
 `Developmental and Child Psychology`,
 `Developmental Biology and Embryology`, 
 `Developmental Services Worker`, 
 `Diagnostic Medical Sonography/Sonographer and Ultrasound Technician`,
 `Diesel Mechanics Technology/Technician`, 
 `Dietetics and Clinical Nutrition Services (Other)`,
 `Dietetics/Dietitian`,
 `Dietitian Assistant`,
 `Digital Arts`, 
 `Digital Communication and Media/Multimedia`, 
 `Digital Humanities`, 
 `Digital Marketing`, 
 `Direct Entry Midwifery`,
 `Directing and Theatrical Production`, 
 `Disability Studies`, 
 `Dispute Resolution`, 
 `Divinity/Ministry`, 
 `Documentary Production`,
 `Drafting and Design Technology/Technician (General)`, 
 `Drafting/Design Engineering Technologies/Technicians (Other)`, 
 `Drama and Dance Teacher Education`, 
 `Drama and Dramatics/Theatre Arts (General)`, 
 `Dramatic/Theatre Arts and Stagecraft (Other)`, 
 `Drawing`,
 `Driver and Safety Teacher Education`, 
 `Early Childhood and Family Studies`,
 `Early Childhood Education and Teaching`, 
 `Early Childhood Program Administration`, 
 `Earth Science Teacher Education`,
 `Earth Systems Science`, 
 `East Asian Languages/Literatures/Linguistics (General)`, 
 `East Asian Languages/Literatures/Linguistics (Other)`,
 `East Asian Studies`, 
 `Ecology`,
 `Ecology and Evolutionary Biology`, 
 `Ecology/Evolution/Systematics and Population Biology (Other)`, 
 `ECommerce/Electronic Commerce`, 
 `Econometrics and Quantitative Economics`, 
 `Economics (General)`,
 `Economics (Other)`, 
 `Economics and Computer Science`, 
 `Economics and Foreign Language/Literature`, 
 `Education (General)`,
 `Education (Other)`, 
 `Education Policy Analysis`, 
 `Education/Teaching of Individuals in Early Childhood Special Education Programs`,
 `Education/Teaching of Individuals in Elementary Special Education Programs`, 
 `Education/Teaching of Individuals in Junior High/Middle School Special Education Programs`,
 `Education/Teaching of Individuals in Secondary Special Education Programs`,
 `Education/Teaching of Individuals Who are Developmentally Delayed`, 
 `Education/Teaching of Individuals with Autism`, 
 `Education/Teaching of Individuals with Emotional Disturbances`,
 `Education/Teaching of Individuals with Hearing Impairments Including Deafness`, 
 `Education/Teaching of Individuals with Intellectual Disabilities`,
 `Education/Teaching of Individuals with Multiple Disabilities`, 
 `Education/Teaching of Individuals with Orthopedic and Other Physical Health Impairments`, 
 `Education/Teaching of Individuals with Specific Learning Disabilities`, 
 `Education/Teaching of Individuals with Speech or Language Impairments`, 
 `Education/Teaching of Individuals with Traumatic Brain Injuries`, 
 `Education/Teaching of Individuals with Vision Impairments Including Blindness`, 
 `Education/Teaching of the Gifted and Talented`, 
 `Educational Administration and Supervision (Other)`, 
 `Educational Assessment/Evaluation/Research (Other)`, 
 `Educational Assessment/Testing/Measurement`, 
 `Educational Evaluation and Research`, 
 `Educational Leadership and Administration (General)`, 
 `Educational Psychology`,
 `Educational Statistics and Research Methods`,
 `Educational/Instructional Technology`, 
 `Educational/Instructional/Curriculum Supervision`, 
 `Electrical and Computer Engineering`, 
 `Electrical and Electronics Engineering`, 
 `Electrical/Electronic Engineering Technologies/Technicians (Other)`, 
 `Electrical/Electronic/Communications Engineering Technology/Technician`,
 `Electrical/Electronics/Communications Engineering (Other)`, 
 `Electromechanical Engineering`, 
 `Electromechanical/Electromechanical Engineering Technology/Technician`, 
 `Electroneurodiagnostic/Electroencephalographic Technology/Technologist`,
 `Elementary and Middle School Administration/Principalship`, 
 `Elementary Education and Teaching`, 
 `Emergency Medical Technology/Technician (EMT Paramedic)`,
 `Emergency Room/Trauma Nursing`, 
 `Endocrinology`,
 `Endodontics/Endodontology`,
 `Energy and Environmental Policy`,
 `Energy Systems Engineering (General)`, 
 `Energy Systems Engineering (Other)`,
 `Energy Systems Installation and Repair Technology/Technician`, 
 `Energy Systems Technology/Technician`, 
 `Energy/Environment/Natural Resources Law`,
 `Engineering (General)`, 
 `Engineering (Other)`,
 `Engineering Chemistry`, 
 `Engineering Design`, 
 `Engineering Mechanics`, 
 `Engineering Physics/Applied Physics`, 
 `Engineering Science`,
 `Engineering Technologies/Technicians (General)`,
 `Engineering/EngineeringRelated Technologies/Technicians (Other)`, 
 `Engineering/Industrial Management`, 
 `EngineeringRelated Fields (Other)`, 
 `EngineeringRelated Technologies/Technicians (Other)`, 
 `English as a Second Language`,
 `English Language and Literature (General)`, 
 `English Language and Literature/Letters (Other)`, 
 `English Literature (British and Commonwealth)`, 
 `English/Language Arts Teacher Education`, 
 `Entomology`,
 `Entrepreneurial and Small Business Operations (Other)`, 
 `Entrepreneurship/Entrepreneurial Studies`,
 `Environmental Biology`, 
 `Environmental Chemistry`, 
 `Environmental Control Technologies/Technicians (Other)`, 
 `Environmental Design/Architecture`, 
 `Environmental Education`, 
 `Environmental Geosciences`,
 `Environmental Health`, 
 `Environmental Science`, 
 `Environmental Studies`, 
 `Environmental Toxicology`, 
 `Environmental/Environmental Engineering Technology/Technician`,
 `Environmental/Environmental Health Engineering`,
 `Environmental/Natural Resource Economics`,
 `Environmental/Natural Resource Recreation and Tourism`, 
 `Environmental/Natural Resources Law Enforcement and Protective Services`, 
 `Environmental/Natural Resources Management and Policy (General)`, 
 `Environmental/Natural Resources Management and Policy (Other)`,
 `Epidemiology`, 
 `Epidemiology and Biostatistics`, 
 `Equestrian/Equine Studies`,
 `Ethics`, 
 `Ethnic Studies`, 
 `Ethnic/Cultural Minority/Gender/Group Studies (Other)`, 
 `European History`,
 `European Studies/Civilization`, 
 `Evolutionary Biology`, 
 `Executive/Career Coaching`,
 `Exercise Physiology and Kinesiology`, 
 `Exercise Science and Kinesiology`, 
 `Experimental Psychology`, 
 `Facilities Planning and Management`,
 `Family and Community Services`, 
 `Family and Consumer Economics and Related Services (Other)`,
 `Family and Consumer Sciences/Home Economics Teacher Education`,
 `Family and Consumer Sciences/Human Sciences (General)`, 
 `Family and Consumer Sciences/Human Sciences (Other)`, 
 `Family and Consumer Sciences/Human Sciences Communication`, 
 `Family Practice Nurse/Nursing`, 
 `Family Psychology`, 
 `Family Resource Management Studies (General)`, 
 `Family Systems`, 
 `Farm/Farm and Ranch Management`, 
 `Fashion Merchandising`, 
 `Fashion/Apparel Design`,
 `Fiber/Textile and Weaving Arts`, 
 `Filipino/Tagalog Language and Literature`,
 `Film/Cinema/Media Studies`,
 `Film/Video and Photographic Arts (Other)`,
 `Finance (General)`, 
 `Finance and Financial Management Services (Other)`,
 `Financial Analytics`,
 `Financial Forensics and Fraud Investigation`,
 `Financial Mathematics`, 
 `Financial Planning and Services`,
 `Fine and Studio Arts Management`,
 `Fine Arts and Art Studies (Other)`, 
 `Fine/Studio Arts (General)`, 
 `Fire Prevention and Safety Technology/Technician`, 
 `Fire Protection (Other)`, 
 `Fire Science/Firefighting`,
 `Fire Services Administration`,
 `Fire/Arson Investigation and Prevention`, 
 `Fishing and Fisheries Sciences and Management`, 
 `Flight Instructor`, 
 `Folklore Studies`,
 `Food Science`, 
 `Food Science and Technology (Other)`, 
 `Food Technology and Processing`, 
 `Foods/Nutrition/Related Services (Other)`,
 `Foods/Nutrition/Wellness Studies (General)`, 
 `Foodservice Systems Administration/Management`, 
 `Foreign Language Teacher Education`, 
 `Foreign Languages and Literatures (General)`,
 `Foreign Languages/Literatures/Linguistics (Other)`,
 `Forensic Anthropology`, 
 `Forensic Chemistry`, 
 `Forensic Nursing`,
 `Forensic Psychology`,
 `Forensic Science and Technology`,
 `Forest Engineering`, 
 `Forest Management/Forest Resources Management`, 
 `Forest Resources Production and Management`, 
 `Forest Sciences and Biology`, 
 `Forestry (General)`, 
 `Forestry (Other)`,
 `French Language and Literature`, 
 `French Language Teacher Education`, 
 `French Studies`, 
 `Funeral Direction/Service`,
 `Funeral Service and Mortuary Science (General)`,
 `Furniture Design and Manufacturing`,
 `Game and Interactive Media Design`, 
 `Gay/Lesbian Studies`,
 `Gene/Genetic Therapy`, 
 `General Literature`, 
 `General Merchandising/Sales/Related Marketing Operations (Other)`,
 `General Studies`, 
 `Genetic Counseling/Counselor`,
 `Genetics (General)`, 
 `Genetics (Other)`,
 `Genome Sciences/Genomics`, 
 `Geochemistry`, 
 `Geographic Information Science and Cartography`,
 `Geography`, 
 `Geography (Other)`, 
 `Geography and Environmental Studies`, 
 `Geological and Earth Sciences/Geosciences (Other)`,
 `Geological/Geophysical Engineering`,
 `Geology/Earth Science (General)`,
 `Geophysics and Seismology`,
 `Geospatial Intelligence`, 
 `Geotechnical and Geoenvironmental Engineering`, 
 `Geriatric Nurse/Nursing`, 
 `German Language and Literature`, 
 `German Language Teacher Education`, 
 `German Studies`, 
 `Germanic Languages/Literatures/Linguistics (General)`,
 `Germanic Languages/Literatures/Linguistics (Other)`, 
 `Gerontology`, 
 `Geropsychology`, 
 `Golf Course Operation and Grounds Management`, 
 `Graphic and Printing Equipment Operator (General) Production`, 
 `Graphic Communications (General)`, 
 `Graphic Communications (Other)`, 
 `Graphic Design`, 
 `Hawaiian Language and Literature`, 
 `Health and Medical Administrative Services (Other)`, 
 `Health and Wellness (General)`, 
 `Health Communication`, 
 `Health Information/Medical Records Administration/Administrator`, 
 `Health Information/Medical Records Technology/Technician`, 
 `Health Law`,
 `Health Occupations Teacher Education`, 
 `Health Policy Analysis`,
 `Health Professions and Related Clinical Sciences (Other)`, 
 `Health Professions Education`,
 `Health Services Administration`, 
 `Health Services/Allied Health/Health Sciences (General)`,
 `Health Teacher Education`, 
 `Health Unit Manager/Ward Supervisor`, 
 `Health/Health Care Administration/Management`, 
 `Health/Medical Physics`, 
 `Health/Medical Preparatory Programs (Other)`,
 `Health/Medical Psychology`,
 `Healthcare Innovation`, 
 `Heavy Equipment Maintenance Technology/Technician`,
 `Hebrew Language and Literature`, 
 `Hematology Technology/Technician`, 
 `Herbalism/Herbalist`,
 `Higher Education/Higher Education Administration`, 
 `Hispanic and Latin American Languages/Literatures/Linguistics (General)`, 
 `HispanicAmerican/Puerto Rican/MexicanAmerican/Chicano Studies`,
 `Histologic Technician`, 
 `Histologic Technology/Histotechnologist`, 
 `Historic Preservation and Conservation (General)`, 
 `Historic Preservation and Conservation (Other)`,
 `History (General)`, 
 `History (Other)`, 
 `History and Language/Literature`,
 `History and Philosophy of Science and Technology`, 
 `History and Political Science`, 
 `History Teacher Education`,
 `Holistic/Integrative Health`, 
 `Holocaust and Related Studies`, 
 `Homeland Security`, 
 `Homeland Security (Other)`,
 `Homeland Security/Law Enforcement/Firefighting and Related Protective Services (Other)`, 
 `Horse Husbandry/Equine Science and Management`, 
 `Horticultural Science`, 
 `Hospital and Health Care Facilities Administration/Management`,
 `Hospitality Administration/Management (General)`, 
 `Hospitality Administration/Management (Other)`, 
 `Hospitality and Recreation Marketing Operations`, 
 `Hotel/Motel Administration/Management`,
 `Hotel/Motel/Restaurant Management`, 
 `Housing and Human Environments (General)`,
 `Housing and Human Environments (Other)`, 
 `Human Biology`,
 `Human Computer Interaction`, 
 `Human Development and Family Studies (General)`,
 `Human Development/Family Studies/Related Services (Other)`, 
 `Human Nutrition`, 
 `Human Resources Development`, 
 `Human Resources Law`,
 `Human Resources Management and Services (Other)`, 
 `Human Resources Management/Personnel Administration (General)`,
 `Human Services (General)`, 
 `Human/Medical Genetics`,
 `HumanCentered Technology Design`,
 `Humanities/Humanistic Studies`, 
 `Hydrology and Water Resources Science`,
 `Illustration`, 
 `Immunology`,
 `Indian/Native American Education`, 
 `Industrial and Organizational Psychology`,
 `Industrial and Physical Pharmacy and Cosmetic Sciences`, 
 `Industrial and Product Design`, 
 `Industrial Engineering`,
 `Industrial Production Technologies/Technicians (Other)`, 
 `Industrial Safety Technology/Technician`, 
 `Industrial Technology/Technician`, 
 `Infectious Disease and Global Health`, 
 `Informatics`, 
 `Information Resources Management`, 
 `Information Science/Studies`, 
 `Information Technology`,
 `Information Technology Project Management`, 
 `Inorganic Chemistry`,
 `Instrumentation Technology/Technician`,
 `Insurance`, 
 `Intellectual Property Law`,
 `Intelligence (General)`,
 `Intelligence/Command Control and Information Operations (Other)`, 
 `Intercultural/Multicultural and Diversity Studies`,
 `Interior Architecture`, 
 `Interior Design`, 
 `Intermedia/Multimedia`, 
 `International Agriculture`,
 `International and Comparative Education`, 
 `International and Intercultural Communication`, 
 `International Business/Trade/Commerce`,
 `International Business/Trade/Tax Law`, 
 `International Economics`, 
 `International Finance`, 
 `International Law and Legal Studies`, 
 `International Marketing`, 
 `International Policy Analysis`, 
 `International Public Health/International Health`, 
 `International Relations and Affairs`, 
 `International Relations and National Security Studies (Other)`,
 `International School Administration/Leadership`,
 `International/Globalization Studies`, 
 `Investments and Securities`, 
 `Iranian Languages/Literatures/Linguistics`, 
 `Irish Studies`,
 `Islamic Studies`, 
 `Italian Language and Literature`,
 `Italian Studies`, 
 `Japanese Language and Literature`, 
 `Japanese Studies`,
 `Jazz/Jazz Studies`, 
 `Jewelry Arts`, 
 `Jewish/Judaic Studies`, 
 `Journalism`,
 `Journalism (Other)`, 
 `Junior High/Intermediate/Middle School Education and Teaching`,
 `Juvenile Corrections`, 
 `Keyboard Instruments`, 
 `Kindergarten/Preschool Education and Teaching`, 
 `Kinesiotherapy/Kinesiotherapist`,
 `Knowledge Management`, 
 `Korean Language and Literature`, 
 `Korean Studies`, 
 `Labor and Industrial Relations`, 
 `Labor Studies`,
 `Lactation Consultant`, 
 `Land Use Planning and Management/Development`, 
 `Landscape Architecture`,
 `Landscaping and Groundskeeping`, 
 `Language Interpretation and Translation`, 
 `Large Animal/Food Animal and Equine Surgery and Medicine`, 
 `Laser and Optical Engineering`, 
 `Latin American and Caribbean Studies`, 
 `Latin American Studies`,
 `Latin Language and Literature`, 
 `Latin Teacher Education`, 
 `Law`, 
 `Law Enforcement Intelligence Analysis`,
 `Law Enforcement Investigation and Interviewing`,
 `Lay Ministry`, 
 `Learning Sciences`, 
 `Legal Administrative Assistant/Secretary`,
 `Legal Assistant/Paralegal`,
 `Legal Professions and Studies (Other)`,
 `Legal Research and Advanced Professional Studies (Other)`, 
 `Legal Studies`,
 `Legal Support Services (Other)`, 
 `Liberal Arts and Sciences (General) Studies and Humanities (Other)`, 
 `Liberal Arts and Sciences/Liberal Studies`, 
 `Library and Information Science`,
 `Library Science (Other)`, 
 `Licensed Practical/Vocational Nurse Training`, 
 `Linguistic/Comparative/Related Language Studies and Services (Other)`, 
 `Linguistics`, 
 `Linguistics and Anthropology`,
 `Linguistics and Computer Science`, 
 `Linguistics of ASL and Other Sign Languages`,
 `Literature (Other)`, 
 `Livestock Management`, 
 `Logic`, 
 `Logistics/Materials/Supply Chain Management`,
 `Long Term Care Administration/Management`,
 `Magnetic Resonance Imaging (MRI) Technology/Technician`, 
 `Management Information Systems (General)`,
 `Management Information Systems and Services (Other)`, 
 `Management Science`, 
 `Management Sciences and Quantitative Methods (Other)`,
 `Manufacturing Engineering`,
 `Manufacturing Engineering Technology/Technician`, 
 `Marine Biology and Biological Oceanography`, 
 `Marine Engineering Technology/Technician`,
 `Marine Science/Merchant Marine Officer`, 
 `Marine Sciences`, 
 `Maritime Studies`,
 `Marketing (Other)`, 
 `Marketing Research`, 
 `Marketing/Marketing Management (General)`,
 `Marriage and Family Therapy/Counseling`, 
 `Mass Communication/Media Studies`, 
 `Massage Therapy/Therapeutic Massage`, 
 `Materials Chemistry`,
 `Materials Engineering`, 
 `Materials Science`, 
 `Materials Sciences (Other)`, 
 `Maternal and Child Health`,
 `Maternal/Child Health and Neonatal Nurse/Nursing`, 
 `Mathematical Biology`, 
 `Mathematical Economics`,
 `Mathematical Statistics and Probability`, 
 `Mathematics (General)`, 
 `Mathematics (Other)`,
 `Mathematics and Computer Science`, 
 `Mathematics and Statistics`, 
 `Mathematics and Statistics (Other)`,
 `Mathematics Teacher Education`, 
 `Mechanical Drafting and Mechanical Drafting CAD/CADD`,
 `Mechanical Engineering`,
 `Mechanical Engineering Related Technologies/Technicians (Other)`, 
 `Mechanical/Mechanical Engineering Technology/Technician`,
 `Mechatronics/Robotics/Automation Engineering`, 
 `Mechatronics/Robotics/Automation Engineering Technology/Technician`, 
 `Medical Anthropology`, 
 `Medical Family Therapy/Therapist`, 
 `Medical Illustration/Medical Illustrator`,
 `Medical Informatics`,
 `Medical Microbiology and Bacteriology`,
 `Medical Office Computer Specialist/Assistant`, 
 `Medical Office Management/Administration`,
 `Medical Radiologic Technology/Science Radiation Therapist`,
 `Medical Science/Scientist`,
 `Medical/Clinical Assistant`, 
 `Medical/Health Humanities`,
 `Medical/Health Management and Clinical Assistant/Specialist`, 
 `Medicinal and Pharmaceutical Chemistry`, 
 `Medicine`, 
 `Medieval and Renaissance Studies`, 
 `Meeting and Event Planning`, 
 `Mental and Social Health Services and Allied Professions (Other)`,
 `Mental Health Counseling/Counselor`,
 `Merchandising and Buying Operations`, 
 `Metal Arts`,
 `Metallurgical Engineering`,
 `Meteorology`, 
 `Microbiological Sciences and Immunology (Other)`, 
 `Microbiology (General)`,
 `Microbiology and Immunology`, 
 `Middle/Near Eastern and Semitic Languages/Literatures/Linguistics (General)`, 
 `Middle/Near Eastern and Semitic Languages/Literatures/Linguistics (Other)`,
 `Military History`,
 `Military Technologies and Applied Sciences (Other)`, 
 `Military Technology and Applied Sciences Management`, 
 `Mining and Mineral Engineering`, 
 `Missions/Missionary Studies`, 
 `Modeling/Virtual Environments and Simulation`, 
 `Molecular Biochemistry`,
 `Molecular Biology`, 
 `Molecular Biophysics`, 
 `Molecular Genetics`, 
 `Molecular Medicine`, 
 `Molecular Pharmacology`,
 `Molecular Physiology`, 
 `Molecular Toxicology`, 
 `Montessori Teacher Education`,
 `Movement Therapy and Movement Education`, 
 `Multi/Interdisciplinary Studies (General)`, 
 `Multi/Interdisciplinary Studies (Other)`, 
 `Multicultural Education`, 
 `Museology/Museum Studies`, 
 `Music (General)`, 
 `Music (Other)`,
 `Music History/Literature/Theory`,
 `Music Management`,
 `Music Pedagogy`, 
 `Music Performance (General)`, 
 `Music Teacher Education`, 
 `Music Technology`,
 `Music Theory and Composition`,
 `Music Therapy/Therapist`, 
 `Musical Theatre`, 
 `Musicology and Ethnomusicology`, 
 `Nanotechnology`, 
 `National Security Policy Studies`, 
 `Natural Products Chemistry and Pharmacognosy`, 
 `Natural Resources and Conservation (Other)`, 
 `Natural Resources Conservation and Research (Other)`, 
 `Natural Resources/Conservation (General)`,
 `Natural Sciences`,
 `Naturopathic Medicine/Naturopathy`, 
 `Naval Architecture and Marine Engineering`, 
 `Near and Middle Eastern Studies`,
 `Network and System Administration/Administrator`, 
 `Neurobiology and Anatomy`, 
 `Neurobiology and Behavior`,
 `Neurobiology and Neurosciences (Other)`, 
 `Neuropharmacology`, 
 `Neuroscience`, 
 `NonProfessional Legal Studies (Other)`,
 `NonProfit/Public/Organizational Management`, 
 `Norwegian Language and Literature`, 
 `Nuclear Engineering`,
 `Nuclear Engineering Technology/Technician`, 
 `Nuclear Medical Technology/Technologist`, 
 `Nuclear Physics`, 
 `Nuclear/Nuclear Power Technology/Technician`,
 `Nurse Anesthetist`, 
 `Nurse Midwife/Nursing Midwifery`,
 `Nursing Administration`,
 `Nursing Education`, 
 `Nursing Practice`,
 `Nursing Science`, 
 `Nutrition Sciences`, 
 `Occupational and Environmental Health Nursing`, 
 `Occupational Health and Industrial Hygiene`, 
 `Occupational Safety and Health Technology/Technician`,
 `Occupational Therapist Assistant`, 
 `Occupational Therapy/Therapist`, 
 `Ocean Engineering`, 
 `Oceanography/Chemical and Physical`,
 `Office Management and Supervision`, 
 `Oncology and Cancer Biology`, 
 `Online Educator/Online Teaching`,
 `Operations Management and Supervision`,
 `Operations Research`,
 `Ophthalmic and Optometric Support Services and Allied Professions (Other)`,
 `Optics/Optical Sciences`, 
 `Optometry`, 
 `Oral Biology and Oral and Maxillofacial Pathology`,
 `Organic Chemistry`, 
 `Organizational Behavior Studies`,
 `Organizational Communication (General)`, 
 `Organizational Leadership`,
 `Ornamental Horticulture`, 
 `Orthodontics/Orthodontology`, 
 `Orthotist/Prosthetist`, 
 `Osteopathic Medicine/Osteopathy`,
 `Outdoor Education`, 
 `Pacific Area/Pacific Rim Studies`, 
 `Packaging Science`, 
 `Painting`, 
 `Paleontology`, 
 `Paper Science and Engineering`, 
 `Parasitology`, 
 `Parks/Recreation/Leisure Facilities Management (General)`, 
 `Parks/Recreation/Leisure Facilities Management (Other)`, 
 `Parks/Recreation/Leisure Studies`, 
 `Parks/Recreation/Leisure/Fitness/Kinesiology (Other)`,
 `Pastoral Counseling and Specialized Ministries (Other)`, 
 `Pastoral Studies/Counseling`, 
 `Patent Law`,
 `Pathology/Experimental Pathology`, 
 `Pathology/Pathologist Assistant`,
 `Patient Safety and Healthcare Quality`,
 `Peace Studies and Conflict Resolution`,
 `Pediatric Dentistry/Pedodontics`,
 `Pediatric Nurse/Nursing`, 
 `Percussion Instruments`,
 `Performance and Sport Psychology`, 
 `Perfusion Technology/Perfusionist`, 
 `Periodontics/Periodontology`, 
 `Perioperative/Operating Room and Surgical Nurse/Nursing`,
 `Personality Psychology`,
 `Petroleum Engineering`, 
 `Petroleum Technology/Technician`,
 `Pharmaceutical Marketing and Management`, 
 `Pharmaceutical Sciences`, 
 `Pharmaceutics and Drug Design`, 
 `Pharmacoeconomics/Pharmaceutical Economics`, 
 `Pharmacology`, 
 `Pharmacology and Toxicology`, 
 `Pharmacology and Toxicology (Other)`, 
 `Pharmacy`, 
 `Pharmacy Administration and Pharmacy Policy and Regulatory Affairs`, 
 `Pharmacy/Pharmaceutical Sciences/Administration (Other)`,
 `Philosophy`,
 `Philosophy (Other)`, 
 `Philosophy and Religious Studies (General)`, 
 `Philosophy and Religious Studies (Other)`,
 `Philosophy/Politics/Economics`, 
 `Photographic and Film/Video Technology/Technician`,
 `Photography`, 
 `Photojournalism`, 
 `Physical and Biological Anthropology`, 
 `Physical Chemistry`, 
 `Physical Education Teaching and Coaching`,
 `Physical Fitness Technician`, 
 `Physical Sciences (General)`,
 `Physical Sciences (Other)`, 
 `Physical Therapy Assistant`,
 `Physical Therapy/Therapist`,
 `Physician Assistant`, 
 `Physics (General)`,
`Physics (Other)`, 
`Physics and Astronomy`, 
`Physics Teacher Education`, 
`Physiology (General)`,
`Physiology/Pathology/Related Sciences (Other)`, 
`Planetary Astronomy and Science`, 
`Plant Genetics`,
`Plant Molecular Biology`,
`Plant Nursery Operations and Management`, 
`Plant Pathology/Phytopathology`, 
`Plant Physiology`, 
`Plant Protection and Integrated Pest Management`,
`Plant Sciences (General)`, 
`Plant Sciences (Other)`, 
`Plastics and Polymer Engineering Technology/Technician`, 
`Playwriting and Screenwriting`,
`Podiatric Medicine/Podiatry`, 
`Political Communication`,
`Political Economy`,
`Political Science and Government (General)`, 
`Political Science and Government (Other)`, 
`Polymer Chemistry`,
`Polymer/Plastics Engineering`, 
`Population Biology`, 
`Portuguese Language and Literature`, 
`Poultry Science`, 
`Power Plant Technology/Technician`, 
`Practical Nursing/Vocational Nursing and Nursing Assistants (Other)`, 
`PreArchitecture Studies`,
`PreArt Therapy`,
`PreDentistry Studies`,
`PreEngineering`,
`PreLaw Studies`,
`PreMedicine/PreMedical Studies`, 
`PreNursing Studies`, 
`PreOccupational Therapy Studies`, 
`PrePharmacy Studies`, 
`PrePhysical Therapy Studies`, 
`PrePhysician Assistant`, 
`Prepress/Desktop Publishing and Digital Imaging Design`, 
`PreTheology/PreMinisterial Studies`, 
`PreVeterinary Studies`, 
`Printing Management`, 
`Printing Press Operator`,
`Printmaking`,
`Professional/Technical/Business/Scientific Writing`,
`Programs for Foreign Lawyers`, 
`Project Management`, 
`Prosthodontics/Prosthodontology`, 
`Protective Services Operations`, 
`Psychiatric/Mental Health Nurse/Nursing`, 
`Psychiatric/Mental Health Services Technician`, 
`Psychology (General)`,
`Psychology (Other)`, 
 `Psychology Teacher Education`, 
 `Psychometrics and Quantitative Psychology`,
 `Psychopharmacology`, 
 `Public Administration`, 
 `Public Administration (Other)`,
 `Public Administration and Social Service Professions (Other)`, 
 `Public Finance`,
 `Public Health (General)`,
 `Public Health (Other)`, 
 `Public Health Education and Promotion`, 
 `Public Health/Community Nurse/Nursing`, 
 `Public Policy Analysis (General)`,
 `Public Policy Analysis (Other)`, 
 `Public Relations/Advertising/Applied Communication`,
 `Public Relations/Advertising/Applied Communication (Other)`, 
 `Public Relations/Image Management`, 
 `Public/Applied History`, 
 `Publishing`, 
 `Purchasing/Procurement/Acquisitions and Contracts Management`, //good until here
 `Quality Control and Safety Technologies/Technicians (Other)`,
 `Quality Control Technology/Technician`, 
 `Rabbinical Studies`, 
 `Radiation Biology/Radiobiology`, 
 `Radiation Protection/Health Physics Technician`, 
 `Radio and Television`,
 `Radio and Television Broadcasting Technology/Technician`, 
 `Radio/Television/Digital Communication (Other)`, 
 `Radiologic Technology/Science Radiographer`, 
 `Radiologist Assistant`, 
 `Range Science and Management`, 
 `Reading Teacher Education`, 
 `Real Estate`,
 `Real Estate and Land Development Law`, 
 `Real Estate Development`,
 `Recording Arts Technology/Technician`, 
 `Regional Studies (U.S./Canadian/Foreign)`, 
 `Registered Nursing/Nursing Administration/Nursing Research and Clinical Nursing (Other)`,
 `Registered Nursing/Registered Nurse`,
 `Regulatory Science/Affairs`,
 `Rehabilitation and Therapeutic Professions (General)`, 
 `Rehabilitation and Therapeutic Professions (Other)`,
 `Rehabilitation Science`, 
 `Religion/Religious Studies`,
 `Religion/Religious Studies (Other)`, 
 `Religious Education`, 
 `Religious Institution Administration and Management`, 
 `Religious Music and Worship (Other)`,
 `Religious/Sacred Music`, 
 `Remote Aircraft Pilot`, 
 `Reproductive Biology`,
 `Research and Development Management`,
 `Research and Experimental Psychology (Other)`,
 `Research Methodology and Quantitative Methods`, 
 `Resort Management`,
 `Respiratory Care Therapy/Therapist`, 
 `Respiratory Therapy Technician/Assistant`, 
 `Restaurant/Culinary/Catering Management/Manager`,
 `Restaurant/Food Services Management`,
 `Retail Management`,
 `Retailing and Retail Operations`, 
 `Rhetoric and Composition`, 
 `Rhetoric and Composition/Writing Studies (Other)`, 
 `Robotics Technology/Technician`, 
 `Romance Languages/Literatures/Linguistics (General)`, 
 `Romance Languages/Literatures/Linguistics (Other)`, 
 `Rural Sociology`, 
 `Russian Language and Literature`, 
 `Russian Studies`, 
 `Russian/Central European/East European and Eurasian Studies`,
 `Sales and Marketing Operations/Marketing and Distribution Teacher Education`,
 `Sales/Distribution/Marketing Operations (General)`, 
 `Sanskrit and Classical Indian Languages/Literatures/Linguistics`, 
 `Scandinavian Languages/Literatures/Linguistics`, 
 `Scandinavian Studies`,
 `School Librarian/School Library Media Specialist`, 
 `School Psychology`,
 `Science Teacher Education/General Science Teacher Education`,
 `Science Technologies/Technicians (General)`, 
 `Science Technologies/Technicians (Other)`, 
 `Science/Health/Environmental Journalism`, 
 `Science/Technology and Society`, 
 `Science/Technology Management`,
 `Science/Technology/Engineering/Mathematics (STEM) Educational Methods`, 
 `Sculpture`, 
 `Secondary Education and Teaching`,
 `Secondary School Administration/Principalship`, 
 `Securities Services Administration/Management`, 
 `Security and Loss Prevention Services`, 
 `Selling Skills and Sales Operations`,
 `Sign Language Interpretation and Translation`,
 `Signal/Geospatial Intelligence`, 
 `Slavic Languages/Literatures/Linguistics (General)`,
 `Slavic Studies`,
 `Small Business Administration/Management`, 
 `Small/Companion Animal Surgery and Medicine`, 
 `Social and Philosophical Foundations of Education`, 
 `Social Entrepreneurship`,
 `Social Psychology`,
 `Social Science Teacher Education`,
 `Social Sciences (General)`, 
 `Social Sciences (Other)`,
 `Social Studies Teacher Education`,
 `Social Work`,
 `Social Work (Other)`, 
 `Sociology (General)`, 
 `Sociology and Anthropology`,
 `Soil Chemistry and Physics`,
 `Soil Science and Agronomy (General)`,
 `Soil Sciences (Other)`, 
 `Solar Energy Technology/Technician`, 
 `Sound Arts`, 
 `South Asian Languages/Literatures/Linguistics (General)`, 
 `South Asian Studies`, 
 `Southeast Asian Studies`,
 `Space Systems Operations`, 
 `Spanish and Iberian Studies`, 
 `Spanish Language and Literature`, 
 `Spanish Language Teacher Education`, 
 `Special Education and Teaching (General)`, 
 `Special Education and Teaching (Other)`,
 `Special Products Marketing Operations`, 
 `Specialized Merchandising/Sales/Marketing Operations (Other)`, 
 `Speech Communication and Rhetoric`, 
 `Speech Teacher Education`, 
 `SpeechLanguage Pathology Assistant`, 
 `SpeechLanguage Pathology/Pathologist`, 
 `Sport and Fitness Administration/Management`, 
 `Sports Communication`,
 `Sports Studies`,
 `Sports/Kinesiology/Physical Education/Fitness (General)`, 
 `Sports/Kinesiology/Physical Education/Fitness (Other)`,
 `Statistics (General)`,
 `Statistics (Other)`, 
 `Strategic Intelligence`, 
 `Stringed Instruments`,
 `Structural Biology`, 
 `Structural Engineering`, 
 `Student Counseling and Personnel Services (Other)`, 
 `Substance Abuse/Addiction Counseling`, 
 `Superintendency and Educational System Administration`,
 `Surgical Technology/Technologist`,
 `Surveying Engineering`, 
 `Surveying Technology/Surveying`, 
 `Sustainability Studies`, 
 `Swedish Language and Literature`, 
 `System/Networking/LAN/WAN Management/Manager`,
 `Systematic Biology/Biological Systematics`,
 `Systems Engineering`, 
 `Systems Science and Theory`,
 `Talmudic Studies`, 
 `Tax Law/Taxation`, 
 `Taxation`,
 `Teacher Education and Professional Development/Specific Levels and Methods (Other)`, 
 `Teacher Education and Professional Development/Specific Subject Areas (Other)`,
 `Teacher Education/Multiple Levels`, 
 `Teaching English as a Second or Foreign Language/ESL Language Instructor`, 
 `Technical and Scientific Communication`,
 `Technical Teacher Education`, 
 `Technical Theatre/Theatre Design and Technology`,
 `Technology Teacher Education/Industrial Arts Teacher Education`,
 `Telecommunications Engineering`, 
 `Telecommunications Management`,
 `Telecommunications Technology/Technician`, 
 `Terrorism and Counterterrorism Operations`,
 `Textile Science`, 
 `Textile Sciences and Engineering`,
 `Theatre and Dance`,
 `Theatre Literature/History and Criticism`, 
 `Theatre/Theatre Arts Management`, 
 `Theological and Ministerial Studies (Other)`, 
 `Theology and Religious Vocations (Other)`, 
 `Theology/Theological Studies`, 
 `Theoretical and Mathematical Physics`, 
 `Theoretical Chemistry`, 
 `Therapeutic Recreation/Recreational Therapy`, 
 `Topology and Foundations`, 
 `Tourism and Travel Services Management`,
 `Tourism and Travel Services Marketing Operations`, 
 `Toxicology`, 
 `Trade and Industrial Teacher Education`,
 `Traditional Chinese Medicine and Chinese Herbology`,
 `Traffic/Customs/Transportation Clerk/Technician`,
 `Transpersonal/Spiritual Psychology`, 
 `Transportation and Highway Engineering`,
 `Transportation and Infrastructure Planning/Studies`,
 `Transportation and Materials Moving (Other)`, 
 `Transportation/Mobility Management`, 
 `Trauma Counseling`,
 `Tribal/Indigenous Law`, 
 `Turf and Turfgrass Management`,
 `UralAltaic and Central Asian Studies`, 
 `Uralic Languages/Literatures/Linguistics`, 
 `Urban Education and Leadership`, 
 `Urban Forestry`,
 `Urban Ministry`,
 `Urban Studies/Affairs`, 
 `Vehicle and Vehicle Parts and Accessories Marketing Operations`,
 `Vehicle Maintenance and Repair Technologies/Technicians (Other)`, 
 `Veterinary Infectious Diseases`, 
 `Veterinary Medicine`, 
 `Veterinary Microbiology and Immunobiology`,
 `Veterinary Office Management/Administration`, 
 `Veterinary Pathology and Pathobiology`, 
 `Veterinary Physiology`, 
 `Veterinary Preventive Medicine/Epidemiology/Public Health`, 
 `Veterinary Sciences/Veterinary Clinical Sciences (General)`, 
 `Veterinary/Animal Health Technology/Technician and Veterinary Assistant`,
 `Virology`,
 `Vision Science/Physiological Optics`,
 `Visual and Performing Arts (General)`, 
 `Visual and Performing Arts (Other)`, 
 `Viticulture and Enology`,
 `Vocational Rehabilitation Counseling/Counselor`, 
 `Voice and Opera`, 
 `Water Resources Engineering`, 
 `Water/Wetlands/Marine Resources Management`, 
 `Web Page/Digital/Multimedia and Information Resources Design`, 
 `Web/Multimedia Management and Webmaster`, 
 `Welding Engineering Technology/Technician`,
 `Welding Technology/Welder`, 
 `Western European Studies`, 
 `Wildlife Biology`, 
 `Wildlife/Fish and Wildlands Science and Management`,
 `Women’s Health Nurse/Nursing`, 
 `Women’s Ministry`, 
 `Women’s Studies`, 
 `Wood Science and Wood Products/Pulp and Paper Technology/Technician`, 
 `Woodwind Instruments`,
 `Worship Ministry`, 
 `Writing (General)`,
 `Yoga Teacher Training/Yoga Therapy`, 
 `Youth Ministry`,
 `Youth Services/Administration`,
 `Zoology/Animal Biology`, 
 `Zoology/Animal Biology (Other)`, 
 `Zymology/Fermentation Science`, 
      ],
    },
  ],
};
